version: '3'
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq-stream
    volumes:
      - ~/dev/.docker/rabbitmq/etc/:/etc/rabbitmq/
      - ~/dev/.docker/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/dev/.docker/rabbitmq/logs/:/var/log/rabbitmq/
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_ERLANG_COOKIE: "RabbitMQ-My-Cookies"
      RABBITMQ_DEFAULT_USER: "admin"
      RABBITMQ_DEFAULT_PASS: "rabbitpassword"
    networks:
      - commerce-network

  zookeeper:
    container_name: zookeeper
    image: wurstmeister/zookeeper
    ports: #주키퍼,카프카 포트는 알아두자
      - "2181:2181"
    networks:
      - commerce-network

  kafka:
    container_name: kafka
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.219.102
      #카프카 토픽 생성
      KAFKA_CREATE_TOPICS: "commerce_member:1:1,commerce_order:1:1,commerce_product:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - ~/dev/.docker/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper
    networks:
      - commerce-network

  memberDatabase:
    image: mariadb
    container_name: memberDatabase
    ports:
      - 3380:3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1112
      MYSQL_DATABASE: member
      MYSQL_USER: memberdb
      MYSQL_PASSWORD: qwer1234
    volumes:
      - ~/dev/.docker/memberDatabase:/var/lib/mysql
    networks:
      - commerce-network

  productDatabase:
    image: mariadb
    container_name: productDatabase
    ports:
      - 3390:3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1112
      MYSQL_DATABASE: product
      MYSQL_USER: productdb
      MYSQL_PASSWORD: qwer1234
    volumes:
      - ~/dev/.docker/productDatabase:/var/lib/mysql
    networks:
      - commerce-network

networks:
  commerce-network:
    external: true