server:
  port: 8000

spring:
  application:
    name: gateway-service
  profiles:
    active: dev
  config:
    import: optional:configserver:http://localhost:8888/

  cloud:
    gateway:
      default-filters:
        - name: GlobalFilter
          args:
            preLogger: true
            postLogger: true

      routes:
        - id: auth-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/oauth2/**, /api/v1/auth/**
          filters:
            - RewritePath=/api/v1/(?<path>.*), /$\{path}
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/v1/users/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/api/v1/users/(?<path>.*), /$\{path}
            - AuthorizationHeaderFilter
        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/orders/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/api/v1/orders/(?<path>.*), /$\{path}
            - AuthorizationHeaderFilter
        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/notification/**

service:
  details:
    - id: view-service
      uri: http://localhost:3000
    - id: user-service
      uri: lb://USER-SERVICE
    - id: order-service
      uri: lb://ORDER-SERVICE

management:
  endpoints:
    web:
      exposure:
        include: gateway

token:
  secret: user_token