spring:
  datasource:
    url: jdbc:mysql://localhost:3306/commerce
    username: shshon
    password: shshon
    driver-class-name: com.mysql.cj.jdbc.Driver

#  redis:
#    lettuce:
#      pool:
#        max-active: 10
#        max-idle: 10
#        min-idle: 2
#    port: 6379
#    host: 127.0.0.1
#    password: redispwd

decorator:
  datasource:
    p6spy:
      enable-logging: true

payment:
  client:
    key: 4860325191563642
    secret: a1186f2244264fd5a4fda77cc1bf7e72d43eec968dfa02e4fa650132515790eb88abf239523c1e0a